export const BASE_PATH = 'http://localhost:3001';
export const PATH = {
  CAREERPATH: '/careerPath',
  COURSESLIST: '/coursesList',
  SKILLPATH: '/skillPath',
  LANGUAGE: '/language',
  ITEMS: '/items',
  SITENAVIGATION: '/siteNavigation',
  POPULARSEARCHES: '/popularSearches',
  FOOTERSITENAVIGATION: '/footerSiteNavigation',
  THEME: '/theme',
  ADMINNAV: '/adminNav',
  KNOWLEDGE: '/knowledge',
};


export const TYPE = {
  ADD_CAREER_DATA: 'ADD_CAREER_DATA',
  ADD_SKILL_DATA: 'ADD_SKILL_DATA',
  ADD_COURSES_DATA: 'ADD_COURSES_DATA',
  ADD_THEME_DATA: 'ADD_THEME_DATA',
  ADD_LANGUAGE_DATA: 'ADD_LANGUAGE_DATA',
  ADD_KNOWLEDGE_DATA: 'ADD_KNOWLEDGE_DATA',

  REMOVE_CAREER_DATA: 'REMOVE_CAREER_DATA',
  REMOVE_SKILL_DATA: 'REMOVE_SKILL_DATA',
  REMOVE_COURSES_DATA: 'REMOVE_COURSES_DATA',
  REMOVE_THEME_DATA: 'REMOVE_THEME_DATA',
  REMOVE_LANGUAGE_DATA: 'REMOVE_LANGUAGE_DATA',
  REMOVE_KNOWLEDGE_DATA: 'REMOVE_KNOWLEDGE_DATA',

  CREATE_CAREER_DATA: 'CREATE_CAREER_DATA',
  CREATE_SKILL_DATA: 'CREATE_SKILL_DATA',
  CREATE_COURSES_DATA: 'CREATE_COURSES_DATA',
  CREATE_THEME_DATA: 'CREATE_THEME_DATA',
  CREATE_LANGUAGE_DATA: 'CREATE_LANGUAGE_DATA',
  CREATE_KNOWLEDGE_DATA: 'CREATE_KNOWLEDGE_DATA',

  CHANGE_KNOWLEDGE_DATA: 'CHANGE_KNOWLEDGE_DATA',
};
