export const BASE_PATH = 'http://localhost:3001';
export const PATH = {
  CAREERPATH: '/careerPath',
  COURSESLIST: '/coursesList',
  SKILLPATH: '/skillPath',
  LANGUAGE: '/language',
  ITEMS: '/items',
  SITENAVIGATION: '/siteNavigation',
  POPULARSEARCHES: '/popularSearches',
  FOOTERSITENAVIGATION: '/footerSiteNavigation',
  THEME: '/theme',
  ADMINNAV: '/adminNav',
  KNOWLEDGE: '/knowledge',
};

export const TYPE = {
  CAREER_ADD_DATA: 'CAREER_ADD_DATA',
  SKILL_ADD_DATA: 'SKILL_ADD_DATA',
  COURSES_ADD_DATA: 'COURSES_ADD_DATA',
  THEME_ADD_DATA: 'THEME_ADD_DATA',
  LANGUAGE_ADD_DATA: 'LANGUAGE_ADD_DATA',
  KNOWLEDGE_ADD_DATA: 'KNOWLEDGE_ADD_DATA',

  CAREER_REMOVE_DATA: 'CAREER_REMOVE_DATA',
  SKILL_REMOVE_DATA: 'SKILL_REMOVE_DATA',
  COURSES_REMOVE_DATA: 'COURSES_REMOVE_DATA',
  THEME_REMOVE_DATA: 'THEME_REMOVE_DATA',
  LANGUAGE_REMOVE_DATA: 'LANGUAGE_REMOVE_DATA',
  KNOWLEDGE_REMOVE_DATA: 'KNOWLEDGE_REMOVE_DATA',

  CAREER_CREATE_DATA: 'CAREER_CREATE_DATA',
  SKILL_CREATE_DATA: 'SKILL_CREATE_DATA',
  COURSES_CREATE_DATA: 'COURSES_CREATE_DATA',
  THEME_CREATE_DATA: 'THEME_CREATE_DATA',
  LANGUAGE_CREATE_DATA: 'LANGUAGE_CREATE_DATA',
  KNOWLEDGE_CREATE_DATA: 'KNOWLEDGE_CREATE_DATA',
  USER_CREATE_DATA: 'USER_CREATE_DATA',

  CAREER_CHANGE_DATA: 'CAREER_CHANGE_DATA',
  SKILL_CHANGE_DATA: 'SKILL_CHANGE_DATA',
  COURSES_CHANGE_DATA: 'COURSES_CHANGE_DATA',
  THEME_CHANGE_DATA: 'THEME_CHANGE_DATA',
  LANGUAGE_CHANGE_DATA: 'LANGUAGE_CHANGE_DATA',
  KNOWLEDGE_CHANGE_DATA: 'KNOWLEDGE_CHANGE_DATA',

  STATUS_LOAD_DATA: 'STATUS_LOAD_DATA',
  STATUS_EMPTY_DATA: 'STATUS_EMPTY_DATA',

  USER_IS_LOGIN: 'USER_IS_LOGIN',
  USER_IS_SIGNIN: 'USER_IS_SIGNIN',
  USER_ADD_TOKEN: 'USER_ADD_TOKEN',

  LOCATION_LAST: 'LOCATION_LAST',
};
